#! /usr/bin/env python3

import os
import sys

try:
    os.setsid()
except Exception as e:
    print(f"btest-setsid failed: {e!r}", file=sys.stderr)
    exit(1)

prog = sys.argv[1]
args = sys.argv[1:]

os.execvp(prog, args)
